services:
    redis:
        build:
            context: .
            dockerfile: redis.Dockerfile
        # volumes:
        #     - redis:/data
    worker:
        build:
            context: ./worker
        env_file:
            - .env.public
            - .env

# For data persistence
# volumes:
#     redis:
#         name: redis
#         external: true
# Don't forget to `docker volume create --name redis`
